version: 1.0.{build}
install:
- cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_build:
- cmd: nuget restore -DisableParallelProcessing
build:
  project: Tedesco.sln
  verbosity: minimal